name: Build Native, Publish Release & Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # STEP 2: Setup GraalVM
      - name: Setup GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      # STEP 3: Create GraalVM configuration files in CI
      - name: Create GraalVM Configuration Files
        run: |
          mkdir -p src/main/resources/META-INF/native-image
          
          # Create native-image.properties
          cat > src/main/resources/META-INF/native-image/native-image.properties << EOF
          Args = -H:+UnlockExperimentalVMOptions \\
                 -H:+ReportExceptionStackTraces \\
                 -H:+AllowDeprecatedInitializeAllClassesAtBuildTime \\
                 --initialize-at-run-time=java.awt.Toolkit \\
                 --initialize-at-run-time=org.apache.poi.ss.format.CellFormatPart \\
                 --initialize-at-run-time=java.awt \\
                 --initialize-at-run-time=sun.awt \\
                 --initialize-at-run-time=sun.font \\
                 --initialize-at-run-time=sun.java2d \\
                 --initialize-at-run-time=sun.font.FontDesignMetrics \\
                 --initialize-at-run-time=java.awt.image,java.lang.Math.PowCache \\
                 --initialize-at-run-time=org.apache.poi.util.RandomSingleton \\
                 --initialize-at-run-time=org.apache.poi.hpsf.PropertySet \\
                 --initialize-at-run-time=org.apache.poi.util.ChainedProperties \\
                 --initialize-at-run-time=org.apache.poi.ss.util.SheetUtil \\
                 --trace-class-initialization=java.awt.Toolkit,org.apache.poi.ss.format.CellFormatPart \\
                 -H:EnableURLProtocols=http,https \\
                 -Djava.awt.headless=true \\
                 -Dapple.awt.headless=true \\
                 -Dorg.apache.poi.ss.disableAutoColumnWidth=true \\
                 -Dorg.apache.poi.ss.format.disable.color=true
          EOF

      # STEP 4: Clean project
      - name: Clean Project
        run: ./gradlew clean

      # STEP 5: Build native executable
      - name: Build Native Executable
        run: ./gradlew nativeCompile -x test --info
        env:
          JAVA_TOOL_OPTIONS: "-Xmx12g -XX:MaxMetaspaceSize=1g"

