name: Build Native, Publish Release & Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # STEP 2: Setup GraalVM
      - name: Setup GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      # STEP 3: Create GraalVM configuration files in CI
      - name: Create GraalVM Configuration Files
        run: |
          mkdir -p src/main/resources/META-INF/native-image
          
          # Create native-image.properties
          cat > src/main/resources/META-INF/native-image/native-image.properties << EOF
          Args = -H:+UnlockExperimentalVMOptions \\
                 -H:+ReportExceptionStackTraces \\
                 -H:+AllowDeprecatedInitializeAllClassesAtBuildTime \\
                 --initialize-at-run-time=java.awt.Toolkit \\
                 --initialize-at-run-time=org.apache.poi.ss.format.CellFormatPart \\
                 --initialize-at-run-time=java.awt \\
                 --initialize-at-run-time=sun.awt \\
                 --initialize-at-run-time=sun.font \\
                 --initialize-at-run-time=sun.java2d \\
                 --initialize-at-run-time=sun.font.FontDesignMetrics \\
                 --initialize-at-run-time=java.awt.image,java.lang.Math.PowCache \\
                 --initialize-at-run-time=org.apache.poi.util.RandomSingleton \\
                 --initialize-at-run-time=org.apache.poi.hpsf.PropertySet \\
                 --initialize-at-run-time=org.apache.poi.util.ChainedProperties \\
                 --initialize-at-run-time=org.apache.poi.ss.util.SheetUtil \\
                 --initialize-at-run-time=org.apache.poi.util.LocaleUtil \\
                 --trace-class-initialization=java.awt.Toolkit,org.apache.poi.ss.format.CellFormatPart \\
                 -H:EnableURLProtocols=http,https \\
                 -H:+AddAllCharsets \\
                 -Djava.awt.headless=true \\
                 -Dapple.awt.headless=true \\
                 -Dorg.apache.poi.ss.disableAutoColumnWidth=true \\
                 -Dorg.apache.poi.ss.format.disable.color=true
          EOF

      # STEP 4: Clean project
      - name: Clean Project
        run: ./gradlew clean

      # STEP 5: Build native executable
      - name: Build Native Executable
        run: ./gradlew nativeCompile -x test --info
        env:
          JAVA_TOOL_OPTIONS: "-Xmx12g -XX:MaxMetaspaceSize=1g -Dnative-image.target-platform=darwin-x86_64"

      - name: Make MCP server executable
        run: chmod +x build/native/nativeCompile/gcp-auditmate-mcp-server

      # 使用預設版本號碼
      - name: Set version
        run: |
          echo "VERSION=20250421.1" >> $GITHUB_ENV
          echo "RELEASE_TAG=v20250421.1" >> $GITHUB_ENV
          echo "RELEASE_NAME=Release v20250421.1" >> $GITHUB_ENV

      # 創建目錄並複製執行檔
      - name: Prepare release files
        run: |
          mkdir -p release
          cp build/native/nativeCompile/gcp-auditmate-mcp-server release/gcp-auditmate-mcp-server-intel
          cd release
          zip -r gcp-auditmate-mcp-server-intel.zip gcp-auditmate-mcp-server-intel

      # 使用 action-gh-release v2 創建 GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            GCP Auditmate MCP Server for Intel Mac
            
            Built on: ${{ github.event.repository.updated_at }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            release/gcp-auditmate-mcp-server-intel.zip
            release/gcp-auditmate-mcp-server-intel

      - name: Upload static site as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
