name: Build Native, Publish Release & Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # STEP 2: Setup GraalVM
      - name: Setup GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      # STEP 3: Create GraalVM configuration file
      - name: Create GraalVM Configuration
        run: |
          mkdir -p src/main/resources/META-INF/native-image
          cat > src/main/resources/META-INF/native-image/native-image.properties << EOF
          Args = -H:+UnlockExperimentalVMOptions \
                 -H:+AllowDeprecatedInitializeAllClassesAtBuildTime \
                 --initialize-at-run-time=org.springframework.util.ClassUtils,org.springframework.util.ConcurrentReferenceHashMap,org.apache.poi.ss.format.CellFormatPart,java.awt.Toolkit \
                 -H:+ReportExceptionStackTraces
          EOF

      # STEP 4: Build native executable
      - name: Build Native Executable
        run: ./gradlew nativeCompile
        env:
          JAVA_TOOL_OPTIONS: "-Xmx12g -XX:MaxMetaspaceSize=1g"

