name: Build Native, Publish Release & Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # STEP 2: Native build
      - name: Setup GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'

      - name: Build Native Executable
        run: ./gradlew nativeCompile
        env:
          JAVA_TOOL_OPTIONS: "-Xmx12g -XX:MaxMetaspaceSize=1g"

